name: feed_finder
description: A library for extracting RSS/Atom feed links from websites, either in <head> or as regular links on the website itself.
version: 1.1.0
homepage: https://github.com/marcjoha/feed_finder

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.1
  html: ^0.15.5

dev_dependencies:
  test: ^1.25.14
  lints: ^3.0.0
